name: MyMedice
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
  
#* flutter pub add
dependencies:
  flutter:
    sdk: flutter

  #* Icons
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  # * Google fonts
  google_fonts: ^4.0.3
  #* Splash Screen
  flutter_native_splash: ^2.2.18
  #* GetX
  get: ^4.6.5
  flutter_map: ^3.1.0
  location: ^4.4.0
  #* Onbording Screen
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.1
  #* Animated Images
  lottie: ^2.2.0
  #* otp 
  flutter_otp_text_field: ^1.1.1
  #* bottom Nav Bar
  google_nav_bar: ^5.0.6
  #* Notification
  #* FireBase
  firebase_core: ^2.8.0
  firebase_auth: ^4.2.2
  #* Cloud FireStore
  latlong2: ^0.8.1
  #* Select Image
  image_picker: ^0.8.7+1
  http: ^0.13.5
  dropdown_search: ^5.0.6
  shared_preferences: ^2.1.0
  flutter_typeahead: ^4.3.7
  flutter_localization: ^0.1.10
  email_validator: ^2.1.17
  flutter_local_notifications: ^8.2.0
  fluttertoast: ^8.2.1
  connectivity_plus: ^3.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/logo/MyMedics.png
  image_dark: assets/logo/MyMedics.png
  android_12:
    image: assets/logo/MyMedics.png
    icon_background_color: "#ffffff"
    image_dark: assets/logo/MyMedics.png
    icon_background_color_dark: "#ffffff"

  web: false

#* flutter pub run flutter_native_splash:create ---->cmd for  create splash screan

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/logo/
    - assets/icons/
    - lib/src/Localisation/ 
    - assets/images/medicel/ctg1/
    - assets/images/medicel/ctg2/
    - assets/images/medicel/ctg3/
    - assets/images/medicel/ctg4/
    - assets/images/medicel/ctg5/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

